### ISSUE TITLE
x-calendar quoting bug for Date object

### ISSUE THREAD

**Issue by operatorjen** [mozbrick/brick#10]
Why does the following work

`<x-calendar chosen='[["2013-07-10", "2013-07-11"]]' controls multiple></x-calendar>`

and the following doesn't work?

`<x-calendar chosen="[['2013-07-10', '2013-07-11']]" controls multiple></x-calendar>`

double/single quote assignment for attributes and arrays should not affect whether it is a valid Date object?

**Comment by ldoubleuz** [comment]
Mostly because JSON.parse is very strict about using double quotes. :(
