### ISSUE TITLE
calendar styling (weekend day)

### ISSUE THREAD

**Issue by Elioty** [mozbrick/brick#101]
Hi

Could you add a specific class to the span.day to specify that they are a weekend day so we could easily apply a different style to them.
Or should we use the custom rendering method?

Elioty.

**Comment by fwenzel** [comment]
"weekend day" might be a definition up to debate, but a class consistent with the day of the week might make sense. This way if someone wants to style all wednesdays, that too would be possible.

**Comment by Elioty** [comment]
Well, by "weekend day", I meant Saturday and Sunday. But I thought about it too : why not a class for every week day, .day-monday .day-tuesday and so on. That would bring more easy styling possibilities without going through the custom rendering method.

**Comment by nadrimajstor** [comment]
Please consider that weekend are not the same day/days everywhere.
http://en.wikipedia.org/wiki/Workweek_and_weekend

**Comment by potch** [comment]
@Elioty your suggestion makes a ton of sense! I'd use the custom renderer for now, but expect to see day-specific classnames soon.

**Comment by potch** [comment]
Moving this to 1.1. Expect it soon!

**Comment by dotch** [comment]
will be tracked in the individual repo at https://github.com/mozbrick/brick-calendar/issues/5
