### ISSUE TITLE
Customizable Date formats

### ISSUE THREAD

**Issue by aegaas** [mozbrick/brick#102]
I'd be nice if the datepicker widget supported custom date formats other than YYY-MM-DD through a format attribute.

I recommend deferring date parsing and formatting to http://momentjs.com/

**Comment by potch** [comment]
We've been discussing using moment for the calendar component, and the concerns are a) file size and b) having a component with a side effect of having a whole library appear when you use it.

**Comment by potch** [comment]
We will likely not be having custom date formatting, due to the large filesize necessary to do so correctly.
