### ISSUE TITLE
Add aria-label tags for accessibility

### ISSUE THREAD

**Issue by nickdesaulniers** [mozbrick/brick#103]
see [this](http://blog.monotonous.org/2013/10/30/firefox-os-app-accessibility-workshop-part-2-analog-clock/) for more info

**Comment by fwenzel** [comment]
@potch is this a dupe?

**Comment by potch** [comment]
If this is a general request for ARIA-label on all components, then it's a dupe. @nickdesaulniers, feel free to re-open if this isn't covered by #91.
