### ISSUE TITLE
Remove/change animation from x-toggle default display

### ISSUE THREAD

**Issue by csuwildcat** [mozbrick/brick#105]
The current animation for x-toggle is lame-stat, and not something that can be GPU'd, let's fix it.

**Comment by fwenzel** [comment]
Why is that? I'm interested in learning which animations can and can't be handled by the GPU and why.

**Comment by csuwildcat** [comment]
@fwenzel this will get you started - we should be doing a perf sweep on all components before v1.0: http://www.html5rocks.com/en/tutorials/speed/high-performance-animations/

**Comment by fwenzel** [comment]
I forgot to say thanks -- I read that and it was enlightening :)

**Comment by pennyfx** [comment]
@csuwildcat  It looks like the animation was removed long ago.  

https://github.com/x-tag/toggle/blob/master/src/toggle.styl
