### ISSUE TITLE
Can't switch tabs on FxOS device

### ISSUE THREAD

**Issue by nickdesaulniers** [mozbrick/brick#107]
Tested on 1.2 Keon.

Since upgrading to 1.9.1, I cannot switch tabs on device!

CC @wfwalker

**Comment by nickdesaulniers** [comment]
status update bump, @potch

**Comment by tofumatt** [comment]
I actually can't switch tabs use `x-tabbar` on ANY device/browser. Tested in Firefox 27 (current Aurora), Firefox OS, Safari, MobileSafari, etc.

**Comment by potch** [comment]
This is fixed up, I believe.

**Comment by tofumatt** [comment]
I will check today and reopen the issue if it's still broken.
