### ISSUE TITLE
Calendar doesn't pick correct date when clicking day in prev or next month

### ISSUE THREAD

**Issue by robhudson** [mozbrick/brick#109]
Before clicking Oct 30th:
![screenshot 2013-11-27 10 40 43](https://f.cloud.github.com/assets/1106/1634076/292b687c-5794-11e3-9baa-3ade3e85b4e2.png)

After clicking it selected Oct 2nd:
![screenshot 2013-11-27 10 40 58](https://f.cloud.github.com/assets/1106/1634086/44395638-5794-11e3-9db8-996ed277d04d.png)

**Comment by xiaoyuandlg** [comment]
Oh, I got the exactly same question on another [C# calendar control](http://www.kettic.com/winforms_ui/calendar_overview.shtml). I read through all the [calendar tutorial](http://www.kettic.com/winforms_ui/csharp_guide/calendar_get_started.shtml) but nothing be found as a good solution.

**Comment by fwenzel** [comment]
@potch @pennyfx  can you confirm or has this since been fixed?

**Comment by potch** [comment]
This is fixed- selecting a date in the prev/next month does not switch months, and selects the day.
