### ISSUE TITLE
TypeError 'mozMatchesSelector' in Firefox on click/tap events

### ISSUE THREAD

**Issue by tofumatt** [mozbrick/brick#111]
I get the lovely error whenever I click/tap in Firefox:

```
TypeError: 'mozMatchesSelector' called on an object that does not implement interface Element.
```

![screenshot 2013-12-04 12 52 53](https://f.cloud.github.com/assets/90871/1675652/a59c7ee0-5d0d-11e3-89d2-b889b4c6fde4.png)

**Comment by potch** [comment]
This is fixed in 0.9.2. Hooray!
