### ISSUE TITLE
Slidebox with tabbar breaks on FirefoxOS when writing on text area

### ISSUE THREAD

**Issue by tehsis** [mozbrick/brick#113]
I've a slidebox which is handled by a tabbar.

Everythings works just fine on almost everything but FirefoxOS. 

http://jsfiddle.net/7Vq4R/1/embedded/result/

If you run that example on a FirefoxOS Device (tested on FirefoxOS 1.1 on Alcatel One Fire and FirefoxOS Simpulator) when you hit the second tabbar and try to write something on the textarea, the slidebox gets broken.

**Comment by fwenzel** [comment]
Nice find! Thanks a lot. The brick team is on holiday break right now but will most definitely take a look after their return. Or, if you feel like it and can pinpoint the issue yourself, you're of course more than invited to submit a pull request. Cheers!

**Comment by tehsis** [comment]
Thanks! I'll take a look to it.

It's nice to know about the holidays since I've made a PR to x-tabbar a
week ago and haven't see any movement there since that :)

Pablo E. Terradillos

**Comment by potch** [comment]
Slidebox is no longer part of Brick - apologies!
