### ISSUE TITLE
Link to jsfiddle and other sites that let you play with Brick "live"

### ISSUE THREAD

**Issue by sole** [mozbrick/brick#116]
Putting this here so we don't forget. Not super urgent but it will encourage people to play.

Maybe we should also have a post on the blog when/if more than one site makes Brick available!

**Comment by fwenzel** [comment]
http://codepen.io/ probably also lets you use it live.

**Comment by sole** [comment]
I'll investigate!

**Comment by potch** [comment]
We should do this- tracking in the new site repo at https://github.com/mozbrick/mozbrick.github.io/issues/10
