### ISSUE TITLE
New components for 1.1

### ISSUE THREAD

**Issue by sole** [mozbrick/brick#117]
In the interests of documenting this without getting lost in discussions somewhere else:
- Shiftbox
- Modal

And my proposal:
- Something akin to ListView so we can scroll over many elements without killing performance

**Comment by csuwildcat** [comment]
Let's discuss this, then break it into discrete issues per-component that are tagged with the appropriate milestone.

**Comment by fwenzel** [comment]
closing this in favor of per-component Issues for 2.0
