### ISSUE TITLE
Large Form Factor Designs?

### ISSUE THREAD

**Issue by potch** [mozbrick/brick#118]
Do some components (`layout` in particular) need to be adjusted for larger format interfaces?

**Comment by sole** [comment]
I was thinking about that too, and wondered whether should it be `layout` or rather the things contained in `layout`? (or both!).

As in, maybe larger fonts, also make the items in the layout not take 100% width but maybe have columns or float (?). But this seems like something that should be done in each contained element, not in the layout itself.

Anyway there goes my 2 cents :moneybag:

**Comment by potch** [comment]
The new responsive attributes in layout solves this pretty dang well :)
