### ISSUE TITLE
Localizing x-calendar

### ISSUE THREAD

**Issue by ldoubleuz** [mozbrick/brick#12]
Need to add support for other languages for month names in x-calendar, either with more labels or with the option to add custom labels

**Comment by fwenzel** [comment]
Even without labels, putting Monday first is a big thing, as countries adhering to ISO_8601 place Monday first.

**Comment by fwenzel** [comment]
(i.e., most countries)

**Comment by ldoubleuz** [comment]
Label-editing addressed in 5c83a7ef22ad0e41df09636e5ecde395cbfe6c1e 
Weekday start editing addressed in 91eeb9a1632895edbf1d302a8c74f7560b58b7ac
