### ISSUE TITLE
x-tabbar with x-flipbox example doesn't do anything

### ISSUE THREAD

**Issue by sole** [mozbrick/brick#120]
http://mozilla.github.io/brick/demos/x-tag-tabbar/index.html

tried it with both Firefox Nightly and Chrome Stable and nothing happens.

In Chrome I also get this error in the console when I click on 'Front' for the first time:
body.scrollLeft is deprecated in strict mode. Please use 'documentElement.scrollLeft' if in strict mode and 'body.scrollLeft' only if in quirks mode.

**Comment by sole** [comment]
Oh and I don't have webcomponents enabled in Nightly, so the world shouldn't be breaking :D

**Comment by fwenzel** [comment]
confirmed!

**Comment by darkwing** [comment]
Just tested, can no longer duplicate.

**Comment by sole** [comment]
What happens with Nightly right now is that right after loading that example the "One" slide is not loaded. If I click on "One" it does load.

**Comment by potch** [comment]
We no longer have the notion of the first card being the default. The bug is definitely with the demo code now :)

**Comment by potch** [comment]
examples are no longer in this repo- tracking over at mozbrick/mozbrick.github.io
