### ISSUE TITLE
Why do things break when dom.webcomponents.enabled = true?

### ISSUE THREAD

**Issue by sole** [mozbrick/brick#124]
Apparently some components in Brick don't work nicely when web components support is enabled in Nightly, which sounds pretty bad (according to @potch `webcomponents.enabled` "break the world", urgh)

My very limited report consisting in testing only two different things shows wild differences:
- flipbox works
- calendar doesn't (`TypeError: this.xtag.calObj is undefined`)

We should look into this, if only because well, it works on Chrome Canary which does have support for web components enabled too.

**Comment by potch** [comment]
The implementation of WC stuff in Firefox lags behind the specification, sometimes considerably. I'm hesitant to dig into this until there's some stability in the spec and in the various browser implementations.

**Comment by sole** [comment]
Since I'm the curious type and I'm investigating the usage/implementation of "raw" web components, I will have a look and see if I find what it actually breaking. I don't promise anything but I'll give it a go, because I find it very annoying to have to enable/disable things when browsing :-)

**Comment by sole** [comment]
@potch I tried this with the latest Nightly, which has the standard-compliant `document.registerElement` implementation, _anddddddd_... **IT WORKSSSSSSSS!**

So very exciting.

I also tried to trace what the root of the issue was, past week. The only thing I could find is that the `this.xtag` object was created when the `created` callback was called. But with the old implementation that never happened. Sadly I couldn't find where was that skipped-between the polyfill and the rest of the magic and my jetlag there was too much haze in my brain :-)

Anyway, we're done here. Happily closing! :cocktail:

**Comment by qqueue** [comment]
I think I'm still having this issue. Both brick and polymer seem to polyfil fine on vanilla firefox 34, but as soon as I set `dom.webcomponents.enabled` to `true`, both projects' web pages break badly, e.g.:

![screenshot from 2014-12-17 22 20 27](https://cloud.githubusercontent.com/assets/1281194/5483935/f57b9e30-863a-11e4-9d35-afaee69385a0.png)

Similar results on 36a2 and 37 nightly. Turning the flag back off makes the site work fine again, in all three firefox versions.

**Comment by sole** [comment]
Yes, this is still an issue. Web components in Firefox registers as "all ready" and so the polyfill that is currently used doesn't kick into action, and so things do not work :-(

**Comment by qqueue** [comment]
That confirms my suspicions, thanks. Do you know which bug tracks a fully working `dom.webcomponents.enabled`? There's the metabug https://bugzilla.mozilla.org/show_bug.cgi?id=811542 , but I dunno if that's more general than getting the feature flag working.
