### ISSUE TITLE
Not selecting any components in the download builder leads to... well, nothing at all actually so that's not good

### ISSUE THREAD

**Issue by leostratus** [mozbrick/brick#127]
Repro:
1. Go to http://mozilla.github.io/brick/download.html
2. Click 'Build Bundle' without selecting any of the checkboxes.
3. ???

'Build Bundle' should either be disabled entirely until some of the app components are selected for inclusion, or if we want to allow a download of X-Tag core without our elements we should inform the user that not selecting any elements just gives you X-Tag core.

Since this is Brick and not X-Tag, I lean toward the first option. We should provide a link/path for people who 'get what Brick is about' but get to the download page wanting to go barebones and write their own elements, so perhaps link to X-Tag. You never know how someone is going to be inspired by a project, and in my opinion having a developer go down either of these paths is a win for us.

**Comment by potch** [comment]
This seems quite reasonable.

**Comment by potch** [comment]
@pennyfx, you want to take a look at disabling "build bundle" until there's a bundle to build?

**Comment by pennyfx** [comment]
Fixed   https://github.com/mozilla/brick/commit/3d2ad4d467ffd84191c91fe795e0d098819dc377

**Comment by pennyfx** [comment]
I added x-tag core to the list of components as "checked" and "disabled".  This allows the user to see that x-tag core is required for our components and is the default download if nothing else is selected.

**Comment by sole** [comment]
I am trying to get the site rebuilt and repushed (without much success I must say, but that's another problem) and I got to see the new version of the download page where x-tag-core is displayed as an existing component... but I don't think that's good UI because that's not a component at all.

We need a better solution.

**Comment by sole** [comment]
I've got the latest version, built it and merged it to `gh-pages`, so we finally don't let the user not select anything. It's deployed now!

We still need to fix this thing where x-tag-core looks like a component, which it technically isn't :-)

**Comment by pennyfx** [comment]
Agreed that it is a little awkward.  My reasoning was that it should be clear what exactly is being packaged together.  

In the future we want to show that Core relies on a polyfill and have that be an optional include.  We also want to show other X-Tag related libs like [Transitions](https://github.com/x-tag/transitions) ,[pseudos](https://github.com/x-tag/pseudo-outer) and skins.   Essentially the packager should not be limited to component elements.

**Comment by potch** [comment]
Currently re-building the download page from scratch, so will track this over on the site repo.
