### ISSUE TITLE
Build Bundle with 0 components selected do nothing 

### ISSUE THREAD

**Issue by sonnyp** [mozbrick/brick#128]
http://mozilla.github.io/brick/download.html

The progress bar will fill and nothing else happens.

**Comment by fwenzel** [comment]
Good find!

**Comment by sole** [comment]
Dupe of #127 ? which is supposedly fixed? Maybe a gh-pages push is in order

**Comment by pennyfx** [comment]
Ya, it's fixed.  Just need to update the site.  

@potch

**Comment by potch** [comment]
Doing this right now!

**Comment by sole** [comment]
Is there any special process before deploying to gh-pages? some sort of build script that needs to be run? It'd be good to know just in case we need emergency out-of-PST support ;-)

**Comment by sole** [comment]
closed as duplicate of #127
