### ISSUE TITLE
We need CONTRIBUTING.md

### ISSUE THREAD

**Issue by sole** [mozbrick/brick#129]

**Comment by potch** [comment]
a-yup.

**Comment by ScottMichaud** [comment]
Just submitted a placeholder one as a... ... building block? :3

**Comment by fwenzel** [comment]
> as a... ... building block?

I see what you did there :surfer:

**Comment by potch** [comment]
I've added the file- let me know if you find it sufficient! https://github.com/mozbrick/brick/blob/master/CONTRIBUTING.md

**Comment by potch** [comment]
Closing this up!

**Comment by sole** [comment]
This is really good!

**Comment by fwenzel** [comment]
<3
