### ISSUE TITLE
turn FirefoxOS UI element to brick

### ISSUE THREAD

**Issue by gasolin** [mozbrick/brick#130]
as shown in http://buildingfirefoxos.github.io/Building-Blocks/

Which make brick the mobile first reusable web component set and also benefit FirefoxOS.

**Comment by gasolin** [comment]
Or if you feel it's fine to mentor someone to do it, add it here https://wiki.mozilla.org/Community:SummerOfCode14

**Comment by gasolin** [comment]
related to the discussion in https://github.com/buildingfirefoxos/Building-Blocks/issues/27

**Comment by potch** [comment]
Work is underway to port ffos elements to Web components- that work will occur outside this project.
