### ISSUE TITLE
grunt site ends up deleting demos/ folder

### ISSUE THREAD

**Issue by sole** [mozbrick/brick#131]
I'm trying to get the site rebuilt so that I can push to gh-pages for #127 but I find that the instructions in https://github.com/mozilla/brick/wiki/Deploying-the-Brick-site lead me to end up without the `demos/` folder

I tried `grunt build`, `grunt site`, all the grunts I could think of, but I can't make this thing work. What's the one weird grunt trick that me and any other contributor that wants to build the site are missing? :question:

**Comment by pennyfx** [comment]
`grunt demos`  ?

**Comment by sole** [comment]
no luck :-(

```
pataleta:brick sole$ grunt demos
Running "demos" task
generating demo pages...
skipped x-tag-appbar; no template.html found
skipped x-tag-calendar; no template.html found
skipped x-tag-deck; no template.html found
skipped x-tag-flipbox; no template.html found
skipped x-tag-layout; no template.html found
skipped x-tag-slider; no template.html found
skipped x-tag-tabbar; no template.html found
skipped x-tag-toggle; no template.html found
```

**Comment by pennyfx** [comment]
Looks like it can't find all the template files that live at `./bower_components/[component]/demo/template.html`    Did you run `bower install`  ?

**Comment by sole** [comment]
Yes and it doesn't change anything. I've also deleted `bower_components` and ran `bower install` again and I still don't have any luck.

**Comment by pennyfx** [comment]
Resolved.

https://github.com/mozilla/brick/commit/11ec7536f5f06961d1b8bb522dd921f066659235
