### ISSUE TITLE
x-iconbutton tag does not preserve CSS class

### ISSUE THREAD

**Issue by wfwalker** [mozbrick/brick#14]
steps to reproduce:
1. create a back button &lt;x-iconbutton class="back"&gt;Back&lt;/x-iconbutton&gt;
2. inspect the element in the browser and see that it has turned into &lt;span class="x-iconbutton-label"&gt;
3. note that the CSS class has not been carried over into the span tag

**Comment by potch** [comment]
We should be striving to preserve attributes on custom elements, adding our own values when needed.

**Comment by pennyfx** [comment]
The custom element should just be creating and wrapping a  `<span>`  so the class="back" should still be on the custom element.

**Comment by ldoubleuz** [comment]
The iconbutton didn't turn into a span, it's just that inspecting the element by rightclicking the button brings up the span that was used to wrap the label for positioning. The x-iconbutton element should be the same class as before.

**Comment by wfwalker** [comment]
ok, my mistake, I copied one of your examples wrong. I got it working. thanks!
