### ISSUE TITLE
Deprecate or de-emphasize tabbar in favor of a better component

### ISSUE THREAD

**Issue by csuwildcat** [mozbrick/brick#140]
We should look at creating an all-around better tabbing component. This could be a semantic, more robust/sturdy tabbox, or a demo of <x-action> that shows how to do switching of a deck/panels.

**Comment by potch** [comment]
What's the rationale? People seem to get the tab motif, which is a set of equally sized triggers for content on a content switching panel. I don't like the notion of tying tabs to their content in a single component, it's too tightly coupled.

**Comment by potch** [comment]
In disucssion outside of this issue, we've come to the conclusion something like the tabbar but with more flexibility should be built, and over time users should be pointed toward that component. Presently being tracked as 'actionbar'.

**Comment by sole** [comment]
Soooo I was going to rewrite the tabview template to use Brick. Does that mean I should wait or can I use the tabbar component already? https://github.com/sole/mortar-tab-view

**Comment by csuwildcat** [comment]
I can get x-action together in short order so Sole can move forward with
that layout - it's a really simple component, and I have time on my hands.

**Comment by sole** [comment]
I guess the layout won't be much different from tabbar - right? I mean I can get started and then we update to whatever once the new component exists.

**Comment by csuwildcat** [comment]
Not too much, the <x-action> elements are going to point at a panel or
content section, and they allow you to fire/call an event/method on the
target, so it can be swapped. I'll get this WIP updated and ready though.

**Comment by potch** [comment]
We are keeping tabbar due to its useful and distinctive styling, but pushing brick-action for most trigger wiring.
