### ISSUE TITLE
Download custom build not working

### ISSUE THREAD

**Issue by leostratus** [mozbrick/brick#141]
See attached screenshot for console output etc.
![screen shot 2014-03-08 at 2 01 40 pm](https://f.cloud.github.com/assets/954624/2366551/77939106-a70d-11e3-84fe-59cc362f0963.png)

**Comment by leostratus** [comment]
Verified this is a bug in Nightly/FF30, not Brick. Will file elsewhere.

**Comment by sole** [comment]
It actually fails on stable too... 
![screen shot 2014-03-08 at 19 32 30](https://f.cloud.github.com/assets/5609/2367103/79fe3288-a73b-11e3-886a-f2f3ad0f0218.png)

Might it be that it is trying to always include a CSS file per tag but there isn't a CSS file for x-tag core?

**Comment by fwenzel** [comment]
Makes sense, how did it break though? Used to work just fine. /me scratches head

**Comment by pennyfx** [comment]
Is it broken?   I tested it with FF 27 on android, Windows and Mac and it
worked.

**Comment by fwenzel** [comment]
Yeah it's broken.

STR:
- latest nightly (though I don't think it matters)
- click core and deck (well, core is always on)
- download.

And you'll see both sole's and Angelina's error messages.

**Comment by pennyfx** [comment]
Right, but as Angelina said, the issue is with FF nightly not Brick.

**Comment by fwenzel** [comment]
/me facepalms. Oh yeah she did say that.

Angelina, have a bug number?
