### ISSUE TITLE
Calendar should have constant height

### ISSUE THREAD

**Issue by waldyrious** [mozbrick/brick#142]
_(Note: I'm not sure whether to report this here or over at [x-tag/calendar](https://github.com/x-tag/calendar); let me know if I should report this issue there instead)_

In the [calendar demo](http://mozilla.github.io/brick/demos/x-tag-calendar/index.html), specifically the one with navigation controls, the height of the calendar changes if the days of the month being displayed cover a different number of weeks (e.g. March 2014 has 6 week rows, while April 2014 has only 5). This causes a "jump" effect, that maybe could be avoided by for example adding a 2em margin to the month or the calendar element, or maybe fixing their height to always be that of 6 weeks. That way, the calendar (and thus its navigation controls) won't get displaced as the user navigates.

**Comment by ryanseys** [comment]
+1 for this little ditty.

**Comment by potch** [comment]
We're looking at a scrolling calendar that wouldn't have this issue. Tracking this in the mozbrick/brick-calendar repo.

**Comment by waldyrious** [comment]
For future reference, this is now being tracked at mozbrick/brick-calendar#2.
