### ISSUE TITLE
The download file contains rc1 files (as well as 1.0.0)

### ISSUE THREAD

**Issue by sole** [mozbrick/brick#145]
Right now if I download the file from the [download page](http://mozilla.github.io/brick/download.html) I get extra files on it:
`
-rwxr-xr-x  1 sole  staff  221328  4 Mar 08:16 OpenSans-SemiBold.ttf
-rwxr-xr-x  1 sole  staff   30768  4 Mar 08:16 brick-1.0.0.css
-rwxr-xr-x  1 sole  staff  158101  4 Mar 08:16 brick-1.0.0.js
-rwxr-xr-x  1 sole  staff   25612  4 Mar 08:16 brick-1.0.0.min.css
-rwxr-xr-x  1 sole  staff   65101  4 Mar 08:16 brick-1.0.0.min.js
-rwxr-xr-x  1 sole  staff   30174  4 Mar 08:16 brick-1.0.0rc1.css
-rwxr-xr-x  1 sole  staff  156229  4 Mar 08:16 brick-1.0.0rc1.js
-rwxr-xr-x  1 sole  staff   25062  4 Mar 08:16 brick-1.0.0rc1.min.css
-rwxr-xr-x  1 sole  staff   64771  4 Mar 08:16 brick-1.0.0rc1.min.js
-rwxr-xr-x  1 sole  staff     712  4 Mar 08:16 readme-1.0.0.txt
-rwxr-xr-x  1 sole  staff     712  4 Mar 08:16 readme-1.0.0rc1.txt
`

**Comment by fwenzel** [comment]
oops. Does the build script need a tweak?

**Comment by pennyfx** [comment]
Can you try this again?  I have not been able to reproduce it anywhere.

**Comment by sole** [comment]
Sorry perhaps I wasn't very obvious. I am referring to the result of downloading the whole Brick bundle.

These are the steps I'm following:

1) go to the download page: http://mozilla.github.io/brick/download.html
2) click **Download Brick** (points to https://github.com/mozilla/brick/releases/download/1.0.0/brick-1.0.0.zip)
![screen shot 2014-03-19 at 11 20 31](https://f.cloud.github.com/assets/5609/2459300/01b27ad4-af59-11e3-92de-b280dcc7eb64.png)

3) open the downloaded zip
4) and there they are! 1.0.0 and rc1 files! :-)

**Comment by potch** [comment]
This is fixed in the latest zip (I accidentally had too many files in my working directory)

**Comment by fwenzel** [comment]
Might want to error out the build script if the git status is dirty.
