### ISSUE TITLE
touch conflict between Brick and Kinetic.js

### ISSUE THREAD

**Issue by katieannemills** [mozbrick/brick#146]
Hi Brick,

Congratulations on 1.0!  I love your product, but while building with it today, I discovered that things break when I try to use Brick 1.0.0 with [Kinetic.js](https://github.com/ericdrowell/KineticJS) 5.0.1.  It seems that Kinetic's logic to follow the mouse around over its `<canvas>` elements for doing hit testing runs into problems in projects that include Brick; to reproduce what I saw in Chrome 33, just grab [this Kinetic example](http://www.html5canvastutorials.com/kineticjs/html5-canvas-set-fill-with-kineticjs/), include Brick (you don't even have to do anything with Brick, just include it), and wiggle your mouse over the shapes; a bunch of errors about undefined variables appear in the console.

It's not too tough to track down what's going on to [this line in Kinetic](https://github.com/ericdrowell/KineticJS/blob/master/kinetic.js#L9293) (9293 in Kinetic 5.0.1, in the definition of `_setPointerPosition`).  When tracking the mouse, Kinetic tests for touch events by seeing if `evt.touches` is undefined, which it is on my laptop when Brick isn't included.  But when Brick is included, a quick console log reveals `evt.touches = []`, an empty array and definitely not undefined.  Hacking around this restores expected behaviour.

So - is this a Brick problem, or a Kinetic problem?  I honestly have no idea, and apologies in advance for bugging you if you think this is a problem for Kinetic - let me know and I'll go ask them instead.

**Comment by sole** [comment]
Hey Bill! Thanks for helping tracking down this mysterious issue.

I suspect it might be something that x-tag/core does.

Can you just include `x-tag-core.js` in your project instead of including the whole Brick suite, and see if this still happens? Then we can invoke the `ma(k|st)ers` of x-tag and ask them about this :)

**Comment by katieannemills** [comment]
Ooops, right you are Sole, the same behaviour appears when just including a freshly downloaded `x-tag-components.js`, so this problem is upstream of brick.  I'll go take my issue over there, thanks!
