### ISSUE TITLE
Font filename misspelled

### ISSUE THREAD

**Issue by fwenzel** [mozbrick/brick#15]
`OpenSans-Semibold.ttf` in `dist/` needs to have an uppercase "b" in "bold". Compare what the CSS file says, and use the exact same spelling :)

@mattbasta pointed it out to me that my app has a 404, and this was why.

Thanks!

**Comment by ldoubleuz** [comment]
Oops, I'm dumb. Just got off the plane, so this is fixed as of 4f8235266db5979f7746c939cc08604cce11ee9e
