### ISSUE TITLE
Brick 1.0.1 Download is 404

### ISSUE THREAD

**Issue by ozten** [mozbrick/brick#153]
STR
1) Load http://mozilla.github.io/brick/ Click Download
2) http://mozilla.github.io/brick/download.html Click Download Brick

Actual:
https://github.com/mozilla/brick/releases/download/1.0.1/brick-1.0.1.zip is a 404

I also tried the custom download builder, which shows a progress bar after clicking "Build Bundle" but then nothing happens. Not sure if that is broken or if I'm missing how to download my bundle.

**Comment by potch** [comment]
This should be working now, my apologies.

**Comment by sole** [comment]
:clap:

**Comment by ozten** [comment]
Verified as AWESOME!
