### ISSUE TITLE
Use Jekyll for some automation in site build

### ISSUE THREAD

**Issue by tofumatt** [mozbrick/brick#155]
So in working on the site in #151, I noticed a fair bit of the site is repeat info that's manually copied across (header tags, version number, etc.). Would you be into converting (or rather, having me convert) the site over to Jekyll so certain bits of data could be rendered out via Jekyll variables?

The content would stay the same, and we could even keep the site in the `master` branch if you wanted (and just merge it into `gh-pages` as happens now), but we could leverage some GitHub Pages variables magic.

**Comment by potch** [comment]
Is this not an issue, now that I've shown you the templates we use?

**Comment by tofumatt** [comment]
Oh, yeah, this is fixed by #151.
