### ISSUE TITLE
x-deck docs say to use "show" but it should be "selected"

### ISSUE THREAD

**Issue by willkg** [mozbrick/brick#158]
The x-deck docs have examples that use "show" in the x-card, but "show" doesn't work. If I use "selected", that works.

Further, it doesn't talk about how to mark an x-card to show by default which seems like a big omission. I know it's something that bit me already.

I'm talking about the docs here:

http://mozilla.github.io/brick/demos/x-tag-deck/index.html

Can someone verify that's correct? If not, can someone correct me? If it is correct, I'm game for doing a PR to fix it.

**Comment by sole** [comment]
Sounds like a documentation issue-API change + not updating the Brick demos! `showCard` is updated in the `x-deck` repo: https://github.com/x-tag/deck#showcardindexelement-direction

I am using a recent version of `x-deck` in this template, you can have a look if you want to see how it looks like: https://github.com/mozilla/mortar-tab-view/blob/master/js/app.js#L5

And of course if you want to play the PR game we're more than interested in that! :D

**Comment by willkg** [comment]
showCard is a js function. I'm talking about the show/selected html attributes. So I think you and I are talking about two different things.

**Comment by fwenzel** [comment]
AFAICT, selected is correct (I've never seen it any other way) and show is wrong, making this a docs bug O_O

**Comment by pennyfx** [comment]
It's looks like the template that this doc is created from is correct.  I think Brick just needs to be rebuilt.

**Comment by willkg** [comment]
If there's anything you think I can do here, let me know. I love doing me some PRs.

**Comment by sole** [comment]
Fork the project, make a new branch, fix the things, send a PR? :-)

**Comment by willkg** [comment]
The last comment from @pennyfx suggests to me the problem will fix itself when brick is rebuilt whatever that means. I'm guessing about that since I've never done brick development before, I have no idea how things are organized and I'm not sure if I'm inferring wrong. I don't want to waste my time or yours.

If there is something that really needs doing and someone can help me understand what needs to be done, I'm happy to do the work. For example, you might say:
- "The docs are wrong. They're in repository at xyz. We need to change 'show' to 'selected'."
- "The docs are wrong, but the site just needs to be rebuilt, so there's nothing you can do here."
- "The docs are right, but confusing. We should add a paragraph along these lines: ..."
- "The docs are wrong. There's documentation on how we maintain brick at xyz. Read that and see if that helps you fix it."

If no one wants to do that, that's fine, but I don't understand enough of what's going on to help right now.

**Comment by willkg** [comment]
Nevermind my last comment. I spent some time with @rlr looking at the code and docs in the x-deck repo and I don't think there's anything I can do here.

**Comment by pennyfx** [comment]
@willkg  Sorry about the vague response, I was on mobile at the time.   

So the docs are generated from a template file in each components repository. 
https://github.com/x-tag/deck/blob/master/demo/template.html

Docs can be rebuilt within Brick by first fetching the latest components using `bower update` then running `grunt demos`.  

No problem @willkg ,  we'll fix it.  

Thanks for pointing it out in the first place.

**Comment by pennyfx** [comment]
Ah hah!  I found that the wrong attribute was being ignored when updating the docs live html view.
https://github.com/x-tag/deck/blob/master/demo/demo.js#L9

This made the docs in the template.html look correct, but then change in the live demo.

https://github.com/x-tag/deck/commit/58db6f72da13a5a112df73c920c6f3a1844822fd
