### ISSUE TITLE
ZIP archive should unzip into a directory

### ISSUE THREAD

**Issue by elsigh** [mozbrick/brick#163]
Instead if unzip-litters into the directory you're in

elsigh@foo:~/Downloads $ unzip brick-1.0.1.zip
Archive:  brick-1.0.1.zip
  inflating: OpenSans-SemiBold.ttf
  inflating: brick-1.0.1.css
  inflating: brick-1.0.1.js
  inflating: brick-1.0.1.min.css
  inflating: brick-1.0.1.min.js
  inflating: readme-1.0.1.txt

**Comment by potch** [comment]
yeah, we could be better citizens in that regard. I'll take this on.

**Comment by potch** [comment]
tracking this in the mozbrick/mozbrick.github.io/ repo instead.
