### ISSUE TITLE
x-toggle, unicode example, failing in Chrome

### ISSUE THREAD

**Issue by cfjedimaster** [mozbrick/brick#164]
The Unicode example here (http://mozilla.github.io/brick/demos/x-tag-toggle/index.html) fails in Chrome. I see a little box, whereas in FF I see a lightning bolt. I can attach a screen shot if you would like.

**Comment by potch** [comment]
You are correct! Will address that, an issue with pseudo-elements.

**Comment by potch** [comment]
At minimum, we should definitely remove the example :)

**Comment by potch** [comment]
Old example has been removed from Brick.
