### ISSUE TITLE
Link to @mozbrick somewhere in the site?

### ISSUE THREAD

**Issue by sole** [mozbrick/brick#166]
I was wondering why the amazing Twitter mozbrick account didn't have more followers and guess what, it's not linked anywhere! Or at least not anywhere prominently.

What about adding a small link to "@mozbrick" in the footer, right next to <3 Mozilla?

**Comment by potch** [comment]
Yup!

**Comment by sole** [comment]
Fixed in https://github.com/mozbrick/mozbrick.github.io/commit/12bde0d950f79de93ce22a06681f433fa87cf60f
