### ISSUE TITLE
update tabbar example to have a default selected tab

### ISSUE THREAD

**Issue by nickdesaulniers** [mozbrick/brick#172]
from [with x-deck](http://mozilla.github.io/brick/demos/x-tag-tabbar/index.html)

**Comment by fwenzel** [comment]
Yeah I think that makes sense.

**Comment by tofumatt** [comment]
Filed a pull request with x-tag and also #173 because of how this system is a bit wonky.

Once the code is landed in x-tag and we update the bower version here this can be fixed.

**Comment by potch** [comment]
Wonkiness confirmed. We're going to move Brick-specific demos to the brick repository and let individual components do their own demos if they so desire.

**Comment by potch** [comment]
We're re-doing the demo pages- will make sure the new demo has this.
