### ISSUE TITLE
x-tag demos in separate repos is really confusing/weird

### ISSUE THREAD

**Issue by tofumatt** [mozbrick/brick#173]
I'm working on #172, and it's really awkward to edit the docs/demo section. It reminds me of the days of updating playdoh-lib/vendor stuff, where I have to update another repo then have it be pushed as a tag **then** update the bower file in brick and build out the new site for my changes to brick's docs to land.

We should host the brick site docs in this repo.

**Comment by potch** [comment]
No argument here. We can find a home in the brick/ repo for the demo/docs templates for each component. I do like the notion of keeping the actual text of the docs within the xtag.json files so long as the components are in their own repos.

**Comment by potch** [comment]
Brick 2.0 has demos in the main site repository.
