### ISSUE TITLE
x-tag-core has platform code

### ISSUE THREAD

**Issue by nsisodiya** [mozbrick/brick#179]
I am new to custom-elements
# First thought 

There is a mismatch between
https://github.com/mozilla/brick/blob/master/dist/x-tag-core.js
& https://github.com/x-tag/core/blob/master/src/core.js
x-tag-core include polyfill code too, which should be removed.
I wish to see one platform.js.

1-- platform.js   (contains all polyfills) 
2-- x-tag/core/blob/master/src/core.js (as it is)
3-- brick.js (remove platform and core xtag library, that is remove item 1 and 2 from current brick.js)

2 is like jQuery
and 3 is like jQuery UI.
So, putting all code in single brick.js is not a good idea.
# 

Second thought,

What is the difference between 
https://github.com/Polymer/platform/blob/master/platform.js
and 
polyfill layer code added inside - https://github.com/mozilla/brick/blob/master/dist/x-tag-core.js
are both codebase exactly same ?

**Comment by nsisodiya** [comment]
I have created small demo http://jsfiddle.net/nsisodiya/266tt/  of x-flipbox without using brick.js (using individual js files)

**Comment by potch** [comment]
We distribute these together for convenience, but will be adding the option to remove the polyfills from the bundle.

**Comment by nsisodiya** [comment]
I guess, Polymer project must also delete https://github.com/Polymer/platform/blob/master/platform.js from their repo !
A joint repo should be created ( like https://github.com/webPlatform/webPlatform/blob/master/webPlatform.js ) which will serve for both project.
