### ISSUE TITLE
Move each component into its own repo

### ISSUE THREAD

**Issue by pennyfx** [mozbrick/brick#18]
Once the components are moved into individual repos I can register them with Bower and add them to the X-Tag Registry.

There are also other advantages like versioning and issue tracking on a per element basis.

**Comment by pennyfx** [comment]
It's looks like there are a lot of dependencies between the custom elements and Brick assets in the demo pages.  I see a bunch of `../../../` stuff.  Can we get away with less bling on the each demo page?

If there are common assets between Brick components, then they will need to be split into a separate repo as well and brought in via bower then crunched together in a Grunt build step.

I'm working through x-datepicker right now to see what needs to change.

I also want to mention that I don't want any of this to interfere with your Brick 1.0 launch.   This is more of a 2.0 or whatever optimization.

**Comment by fwenzel** [comment]
Makes sense, thanks for taking a look, Arron!

**Comment by pennyfx** [comment]
I converted Datepicker.  https://github.com/x-tag/datepicker.

To make component self contained with the repo, I had to simplify the demo and remove all `../../../` references that dropped out of the repository.   All the remaining demo dependencies are in `demo/x-tag-components.(js | css)` and are updatable by running `bower install && grunt build`. 

There are some shared Sass styles between all? elements in Brick that I moved to a separate repo.   https://github.com/pennyfx/brick-component-base   I registered it as `brick-component-base-test1` in bower for now.  We can pick a better name later.  Then, I added a dependency reference in bower.json so it will be downloaded with `bower install`.  Next, I added a section in Grunt.js that takes care of the Sass compilation.  The janky part is that I had to add this `includePaths: ['components/brick-component-base-test1/src/'` to get the Sass `@imports` to work.    But other than that, it was pretty darn easy.

I also added  `x-datepicker` to Bower, so anyone can install it by running `bower install x-tag-datepicker` or by adding it to their project's `bower.json` file.   Example:  https://github.com/x-tag/x-tag/blob/master/bower.json#L10

Summary:
Remove all `../../../` that drops out of the repo.
Common Brick styles/js should be moved to a separate repo.
Any component dependencies should be listed in bower.json and be registered with Bower.
Sass compilation is easy with grunt-sass.   https://github.com/x-tag/datepicker/blob/master/Gruntfile.js#L25
Demos for individual components should be simple.
Complicated demos showing component composition should be moved to Brick. (showcase)

Overall it was pretty easy to convert this component.  Ping me if you have questions.

**Comment by zenorocha** [comment]
+1

I agree we should move each Brick component to a different repo.

I'm the creator of [customelements.io](http://customelements.io/), which is a gallery for Web Components and we're registering via Github repo.

For this reason only `appbar`, `flipbox`, `layout`, `modal`, `slidebox`, `toggle` are featured there.

**Comment by potch** [comment]
This is finished!
