### ISSUE TITLE
Would like smaller download option

### ISSUE THREAD

**Issue by GrosSacASac** [mozbrick/brick#180]
I visited the brick doc and downloaded the flipbox thing. I then took a look at the js and css and it was so so big. Too big for my project (where I have other must-big files). Make it smaller or reduce it.

**Comment by pennyfx** [comment]
We're working on a more granular downloader for Brick, but in the mean time checkout X-Tags.org download page. http://www.x-tags.org/download    You can pick and choose what dependencies you want.   Also, I should mention that majority of the size of web components comes from the polyfills that are required for older browsers.

**Comment by fwenzel** [comment]
You can also build your own bundle here and just select flipbox: http://mozilla.github.io/brick/download.html

This brings the minified size to a total of 40k, or well smaller than a single picture in your project.

Also, as web components become established in browsers, at some point, you will not have to use polyfill code anymore; until then, there is some overhead, though that overhead gets smaller and smaller the more components you use.
