### ISSUE TITLE
What's the reason for moving brick way of using x-tags under the hood

### ISSUE THREAD

**Issue by 0x-r4bbit** [mozbrick/brick#198]
While I actually like the fact that Brick embraces native web components technologies, I still wonder why the decision has been made that it doesn't use x-tags under the hood anymore.

**Comment by potch** [comment]
I have a blog post coming that explains all this- stay tuned!

**Comment by 0x-r4bbit** [comment]
@potch great thanks, but where can I follow these updates?

**Comment by dotch** [comment]
@PascalPrecht the blog post and future updates can be found on the brick-blog at:
http://mozbrick.github.io/blog/

**Comment by 0x-r4bbit** [comment]
@dotch thank you!

**Comment by waldyrious** [comment]
Any chance the blog can get an RSS feed?

**Comment by fwenzel** [comment]
It's jekyll, it prob already has one? @potch ?
