### ISSUE TITLE
Port Appbar to Brick 2.0

### ISSUE THREAD

**Issue by rorito** [mozbrick/brick#199]

**Comment by sole** [comment]
bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1040046

**Comment by dotch** [comment]
added appbar, see #223

**Comment by sole** [comment]
brilliant, I'll update (read = close) the bugzilla issue!

**Comment by sole** [comment]
oh it was closed already. even better! Thanks @dotch! \o/

**Comment by fwenzel** [comment]
What are the styles on this? Since we don't have separate style Issues, can't close this without it looking like Gaia.

**Comment by dotch** [comment]
gaia style for appbar is currently tracked here:
https://github.com/mozbrick/brick-appbar/issues/1
but we can also reopen this issue since i closed it too early.
