### ISSUE TITLE
On brick's website, overflow: hidden the flipping

### ISSUE THREAD

**Issue by fwenzel** [mozbrick/brick#20]
Since the demo shows a stylized phone, the transition should probably not break out of the phone's screen.

Though admittedly, that would be pretty cool in real life.

**Comment by sole** [comment]
```
Though admittedly, that would be pretty cool in real life.
```

I wish I could favorite that, or upvote it, or re-issue it (it'd be akin to retweeting but in github context)

**Comment by csuwildcat** [comment]
I noticed this too, and would add one suggestion: beyond simply adding `overflow: hidden`, we could modify the transition so it translated the Z axis back as it flipped - this way it would keep the edges in view. Perhaps that behavior is best served as an optional, boolean attribute, like `contain-flip` (we probably can think of a better name)

**Comment by potch** [comment]
This demo is no longer on the Brick homepage.
