### ISSUE TITLE
Port ListView to Brick 2.0

### ISSUE THREAD

**Issue by rorito** [mozbrick/brick#200]
and uplift to brick site, bower repo, etc

**Comment by sole** [comment]
In bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1039473

**Comment by potch** [comment]
I'll need to do a bit more style work before I close this up.

**Comment by fwenzel** [comment]
<3

**Comment by dotch** [comment]
added to mozbrick, including styling.
further issues will be tracked in 
https://github.com/mozbrick/brick-listview
