### ISSUE TITLE
Gaia 2.0 style for Brick Action Menu

### ISSUE THREAD

**Issue by rorito** [mozbrick/brick#210]
Gaia 2.0 PSD
https://www.dropbox.com/sh/klpt0h6pfe2rjn7/AADUs0J_XEsQEsOPH9qlyvZwa

Gaia 2.0 CSS examples (by Casey & Wilson)
https://github.com/caseyyee/gaia-controls
http://caseyyee.github.io/gaia-controls/src/app/index.html

Existing Gaia 1.3 Action Menu
http://buildingfirefoxos.com/building-blocks/action-menu.html

**Comment by potch** [comment]
For potential components, assume the issue cannot be fixed unless the component is properly styled.
