### ISSUE TITLE
Create Brick Confirmation dialog

### ISSUE THREAD

**Issue by rorito** [mozbrick/brick#213]
This could be done as a broader modal dialog that we modify into Confirm, Alert, Action, etc.
The Gaia 2.0 dialogs make the background slightly opaque and seem to float in the middle of the screen.

http://caseyyee.github.io/gaia-controls/src/app/index.html
http://caseyyee.github.io/gaia-controls/src/app/.dialogue-confirm

**Comment by nicola** [comment]
Working on it here: [nicola/brick-dialog](https://github.com/nicola/brick-dialog)
You can see it working here: http://nicola.github.io/brick-dialog/

Critics and comments before it gets into brick wanted! Starting from the naming whether it should be `brick-dialog` or `brick-modal`
