### ISSUE TITLE
Create Brick Menu

### ISSUE THREAD

**Issue by rorito** [mozbrick/brick#215]
Simple Menu wired up using brick-action. 

See styling and effects in the Menu section here:
http://caseyyee.github.io/gaia-controls/src/app/index.html

**Comment by nicola** [comment]
I think one should use brick-action independently inside that. I am now building a set of examples but for the moment:

``` html
<brick-menu>
    <brick-action target="important" action="toggle">Toggle</brick-action>
    <a href="/home">Go home</a>
</brick-menu>
```

**Comment by nicola** [comment]
You can find this live: http://nicola.github.io/brick-menu/

**Comment by dotch** [comment]
brick-menu (including styling) has been added to mozbrick.
further issues will be tracked in 
https://github.com/mozbrick/brick-menu
