### ISSUE TITLE
Creatd Brick-Progressbar

### ISSUE THREAD

**Issue by nsisodiya** [mozbrick/brick#233]
Hello Everybody here,
      I am very much interested in web Components.
I have created Brick-Progressbar.
Demo - http://nsisodiya.github.io/brick-progressbar/
Codebase - https://github.com/nsisodiya/brick-progressbar

1) I would like to know that How this code can be included in main Brick repo.
2) If Brick developer think that this code is not useful then I will change rename it.
3) I need 2-3 days more to complete this project, it will be great if somebody can review my code and help me understand my mistake !

**Comment by fwenzel** [comment]
How cool! I have a random question: What does it do that `<progress>` doesn't? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress

**Comment by potch** [comment]
Thanks for the contribution! @dotch is going to review the code. If tweaks are needed, we can either transfer the repository to the mozbrick organization or fork the repository into the mozbrick organization.

**Comment by nsisodiya** [comment]
@fwenzel , 

<progress> element do not have attribute like "showStatus", "showPercentage" "striped" , "active", Also <process> do not contains "min" attribute. At the same time, <process> do not contains animation. look and feel is different for every browser. 

In case, if you are hinting that "Why we need <brick-progressbar> when we have <progress>" then here is my long answer.

AFAIK - The whole point of web-components is to provide is base Layer using which developer can add their Custom Elements (tags). 
IMO, there is no need to make specification of <progress> , <section> and all such elements and wait for Browser vendor to implement them and then wait for developer to create fancy style-sheets over them so that the same process element will look exactly same in every platform and as well as include some polyfills because you have to support older browsers too.

This whole process is not at all needed If Browser vendor create a well defined layer over which developers like us can create custom tags (elements).
By this process, we will be having lots of alternate for same element & that is beauty of Open Source.

**Comment by nsisodiya** [comment]
@potch Thanks for +ve reply.

**Comment by nsisodiya** [comment]
@dotch & @potch 
    waiting for reply at - https://github.com/nsisodiya/brick-progressbar/issues/1

**Comment by nsisodiya** [comment]
@potch @dotch  - I am done from my side, Please fork or transfer this repo. Only CSS related changes are remaining which can be done later. My skills on CSS is are not excellent.
See demo on final code from my side - http://nsisodiya.github.io/brick-progressbar/

**Comment by lmorchard** [comment]
It looks like this has been transferred...? (not sure when or whom by)

https://github.com/mozbrick/brick-progressbar
http://mozbrick.github.io/brick-progressbar/

Can we close this issue?

**Comment by dotch** [comment]
Styling is still missing, but there is a corresponding issue on the component repo. So this can be closed.
