### ISSUE TITLE
brick-menu inside of brick-deck does not render initially

### ISSUE THREAD

**Issue by robdodson** [mozbrick/brick#234]
If I have a brick-menu inside of a brick-deck I need to toggle the deck card offscreen and then back on to actually see the menu

**Comment by potch** [comment]
@robdodson make sure you have the card you would like `selected` by default. If it's still not working, will investigate.

**Comment by robdodson** [comment]
ah ok that fixed it. I think I only had `selected-index` set. Is there a reason why I need to set both attributes? It seems like I'd always want `selected-index` and `selected` to match the same element. Could `selected-index` just place `selected` on whichever child matches the index when it starts up?

**Comment by potch** [comment]
We'll fix brick-deck so if either is set at initialization, the other will be properly initialized.

**Comment by kentaromiura** [comment]
This has been fixed through 
https://github.com/mozbrick/brick-deck/commit/e4c9cd2ee144a062efa40f0d86df9203d486b0ab 
and https://github.com/mozbrick/brick-deck/commit/ce6dfc9ea3e5ab22dcc7e35a8fcf4ba4a3756a6e

now you can either use selected-index or just place a selected attribute to any child.

**Comment by robdodson** [comment]
Awesome, thanks!
