### ISSUE TITLE
Create brick-select

### ISSUE THREAD

**Issue by potch** [mozbrick/brick#237]
A nicer, mobile-friendly wrapper around a `<select>`. Allow multi-select as well.

**Comment by lmorchard** [comment]
I could try taking a swing at this one after brick-action-menu is wrapped up

**Comment by nicola** [comment]
I was going to assign this to me. @lmorchard are you working on it?

**Comment by lmorchard** [comment]
[I've started poking at it](https://github.com/lmorchard/brick-select), but I don't have access to assign brick issues to myself

**Comment by fwenzel** [comment]
Dude, speak up, those rights can be fixed...
![](http://www.dhs.gov/sites/default/files/images/opa/S4_Rect.jpg)

**Comment by lmorchard** [comment]
Created [mozbrick/brick-select](https://github.com/mozbrick/brick-select), but it's just the initial import from `yo brick` right now. Keeping this issue open until I've got at least a first functional version.

**Comment by lmorchard** [comment]
So, I've created a `brick-select`, and I think it's fairly functional for a first go round:

https://github.com/mozbrick/brick-select/
http://mozbrick.github.io/brick-select/

Closing this issue. Go ahead and file issues on that component for further stuff & things.
