### ISSUE TITLE
Interdependece of components triggers a double registration element error

### ISSUE THREAD

**Issue by nicola** [mozbrick/brick#257]
1. I am developing brick-button that depends on brick-action, **so I am importing src/brick-action**  from bower components
2. I want to use also brick-action, **so I am importing dist/brick-action** from bower components

So unless I vulcanize (good practice for production) I will have imported the brick-action twice.
**But** when in development mode for a peaceful non-suicidal debugging, you may want to do this:

``` javascript
if (!window.BrickActionElement) {
  window.BrickActionElement = document.registerElement('brick-action', {
    prototype: BrickActionElementPrototype
  });
}
```

or we will get the following error

> Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'brick-action'. A type with that name is already registered.

**Comment by dotch** [comment]
fixed in all components
