### ISSUE TITLE
Brick logo is missing on Android stock browser

### ISSUE THREAD

**Issue by csuwildcat** [mozbrick/brick#26]
This affects Android stock browser as recent as the Galaxy S4 running Android 4.3

**Comment by ldoubleuz** [comment]
Probably because Android Browsers <= 2.3 can't support SVG images, whoops.

**Comment by csuwildcat** [comment]
This is being observed on the stock browser for Android 4.3, on a Galaxy
S4...

**Comment by ldoubleuz** [comment]
Whoops, forgot to close this. Should be fixed as of 66692ce0e3af72c1a5cd590732931eb0bf49261f
