### ISSUE TITLE
Add Ideal Browser Support

### ISSUE THREAD

**Issue by brennanmceachran** [mozbrick/brick#27]
Is this a latest version of modern browsers only thing? Or are we aiming to support ie8+?

**Comment by ldoubleuz** [comment]
This library is built on [x-tags](http://www.x-tags.org/), so for now, we can use those as the ideal support. (However, the exception is anything with flexbox, like x-layout or x-togglegroup will require IE10).

I'm hesitant to claim stable support for them in light of some of these bug reports, but these are the ideal at least.

**Comment by umhan35** [comment]
I think we need to put this information somewhere explicitly.

**Comment by potch** [comment]
Testing grid support (coming in Brick 2) will answer these questions definitively.

**Comment by potch** [comment]
Tracking this in https://github.com/mozbrick/brick/issues/222.
