### ISSUE TITLE
Missing font from download?

### ISSUE THREAD

**Issue by cfjedimaster** [mozbrick/brick#32]
Running a simple calendar demo I see this in the Network panel:

http://localhost/testingzone/bricktests/brick/OpenSans-SemiBold.ttf

The font is not included with the download. It certainly doesn't prevent me from playing with Brick, but I assume that this font should be removed from the CSS perhaps? Or included w/ the download?

**Comment by ldoubleuz** [comment]
Whoops, good catch, I'll update the Makefile/release bundle soon.

**Comment by ldoubleuz** [comment]
Fixed as of version [1.0.3beta](https://github.com/mozilla/brick/releases/tag/1.0.3beta)
