### ISSUE TITLE
demo bug in home

### ISSUE THREAD

**Issue by tychio** [mozbrick/brick#34]
![brick](https://f.cloud.github.com/assets/1452817/999155/4431fb72-0a23-11e3-9c9a-0a2dc69c5a46.png)

the content is overflow.

**Comment by ldoubleuz** [comment]
Whoops, I'm dumb and accidentally committed some testing code. Should be fixed soon.

**Comment by ldoubleuz** [comment]
Fixed in 1601672d6a3b90e14a0d412020e72a0d3a7be86f
