### ISSUE TITLE
Safari no-go

### ISSUE THREAD

**Issue by kently** [mozbrick/brick#35]
Demos work great for me in Win7 Firefox, but not in Safari (not Win7, OS X nor iOS).

Not being able to play with it in a mobile browser makes this a nonstarter for me at the moment.

**Comment by ldoubleuz** [comment]
Thanks for bringing this up. Turns out this is actually because the current version of x-tags' implementation of custom events is broken in Safari. I've filed a bug [here](https://github.com/x-tag/core/issues/24), and I'll update this when this changes.

**Comment by igorshubovych** [comment]
Same applies to Mobile Safari.
So it basically does NOT work on iPhone and iPad.

**Comment by fwenzel** [comment]
Thanks for bringing it up, it's not intentional and we'll fix it in the underlying web component library!

**Comment by potch** [comment]
Fixed by f1eec67a.

Let us know if you see any specific iOS issues!
