### ISSUE TITLE
Add Hamburger-style menu shift component

### ISSUE THREAD

**Issue by potch** [mozbrick/brick#36]
Would be a nice companion to Deck.

**Comment by fwenzel** [comment]
Agreed! Also a pretty common thing to do in apps.

**Comment by ldoubleuz** [comment]
Sounds good, I'll start working on it after I've settled into my schedule this week.

**Comment by csuwildcat** [comment]
This component is the x-shiftbox, it was intended to handle this exact use-case. Let's revitalize/rework that component and get it to production quality instead of creating a completely different one.'

Here's what I'd like to see us evolve x-shiftbox into, because it's completely, totally, 100% badass: http://tympanus.net/Development/MultiLevelPushMenu/

**Comment by stevesouth** [comment]
+1 for a menu component, this seems to be the biggest missing feature at the moment. 

The link above is nice especially the UX for the sub menu which can be tricky. However it is quite laggy on mobile so it will need to be optimised with the hardware accelerated 'translate' property (sure you guys know that, I haven't had a chance to look a the brick code yet). 

For the menu itself some apps have it pushing the main content out if the way and some have it floating over the top. It would be nice if brick supported both options. Finally, the main content usually dims when the menu is open. 

Great work in the framework, seems to be coming along nicely.

**Comment by pennyfx** [comment]
I added our existing x-shiftbox which by default acts like a hamburger menu.    https://github.com/mozilla/brick/commit/89e0824e1ed113e8d48653903b320e5d2424e28a

**Comment by pennyfx** [comment]
I guess we're not shipping this component with 1.0.    It's ready to be included at any time though.

**Comment by pennyfx** [comment]
Moved to 1.1 Milestone

**Comment by fwenzel** [comment]
x-layout exists™ in Brick 2.0
