### ISSUE TITLE
Components Sidebar Dropping too low

### ISSUE THREAD

**Issue by sayak-sarkar** [mozbrick/brick#37]
The Components Sidebar is positioned a bit too low and as such tooltip menu option is hidden while scrolling down the page. This might be resolved possibly reducing the top margin for the Components Menu.

Attaching a screenshot of the page to better explain the issue:-

![bricks components menu](https://f.cloud.github.com/assets/1418735/1034616/4b58d1f2-0f1c-11e3-9080-87aa17b66fec.png)

**Comment by potch** [comment]
I'll take this, and tweak the sidebar to scroll instead of clip.

**Comment by potch** [comment]
The new brick site addresses this!
