### ISSUE TITLE
Migrate component styles to Stylus?

### ISSUE THREAD

**Issue by potch** [mozbrick/brick#45]
Sass is nice! except that it adds ruby to our build stack. Would be awesome to move to Stylus, a JS-based CSS preprocessor. Thoughts?

**Comment by sole** [comment]
Great idea! I'd like to see stylus in action too. I can help with this if you need any extra pair of eyes/hands.
Or maybe even documenting how to build-is the current sass step documented anywhere? I didn't see it in the Makefile.

**Comment by potch** [comment]
@ldoubleuz I'd love to get your okay on this before we go forward!

**Comment by fwenzel** [comment]
Stylus would have the added beauty of economies of scale from other teams at Mozilla (most notably, Marketplace) also using it. This overlap can be helpful.

@sole I'm afraid I can only let you lend your eyes OR hands to this bug, not both. :laughing:

**Comment by ldoubleuz** [comment]
@potch Sure thing! I'm okay with converting to using Stylus to simplify the build stack.

**Comment by potch** [comment]
Sweet, going to get cracking on this immediately.

**Comment by potch** [comment]
I have some strawman stuff hanging out over here: https://github.com/mozilla/brick/compare/stylus Not ready for merge yet, but would love feedback. Going to change the name of `foundation` as there's an established CSS framework with that name.

**Comment by pennyfx** [comment]
@potch It looks like this creates a Brick dependency in the Calendar by having to reference ../../../mixins, etc..  

If we break the common styles into another repo and use Bower, then the stylus import becomes  ../bower_components/brick-common/mixins.   This allows the element to be built in isolation and all dependencies are local to the element.  This is how js and css dependences are already handled on every component at github.com/x-tag/.

Another benefit of having these styles in a repo is that contributors can easily clone them and come up with their own styles without having to clone all of Brick.  We could essentially create skin packs like this and one could choose a skin pack by running something like `bower install ffos-skin-silver`, then run a build command.     

What do you think?

**Comment by potch** [comment]
@pennyfx totally. I just placed those files in that location for the purposes of getting this started. When things are split up that approach makes complete sense.

**Comment by navaru** [comment]
I would suggest to use visionmedia/rework instead of stylus, it offers greater flexibility.

**Comment by potch** [comment]
Fixed by 2b267eea.
