### ISSUE TITLE
Separate Functional and Visible styles

### ISSUE THREAD

**Issue by potch** [mozbrick/brick#46]
I'd like each component to have a functional style file and a visual style file that we can optionally leave out in favor of other skins.

I'm volunteering to do this separation as part of the stylus migration.

**Comment by fabiomagnoni** [comment]
@potch I'm happy to help you on it.

**Comment by potch** [comment]
The separation has landed! 2b267eea separated each component's styles between 'scaffold' and 'skin' files, respectively. Leaving this issue open to track the ability to exclude the default skin in favor of an alternate.

**Comment by fwenzel** [comment]
docs++

**Comment by potch** [comment]
ya docs would be nice :)

**Comment by potch** [comment]
Closing this in favor of https://github.com/mozilla/brick/issues/82
