### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by arasbm** [mozbrick/brick#49]
I just noticed http://mozilla.github.io/brick/index.html is down. I don’t know how else to contact you, so I create this issue hoping you get an email. Here is the error on homepage:

```
Error 503 Backend is unhealthy

Backend is unhealthy
Guru Meditation:

XID: 3654671732

Varnish cache server
```

**Comment by ldoubleuz** [comment]
Hmm, I'm afraid I'm unable to reproduce the error. It may have been a temporary issue.
