### ISSUE TITLE
Add a nuget package

### ISSUE THREAD

**Issue by maitredede** [mozbrick/brick#50]
Hi,

Do you think it can be possible to maintain a [Nuget](https://www.nuget.org/) package ? 

Thanks.

**Comment by pennyfx** [comment]
I'll look into it.

**Comment by pennyfx** [comment]
https://www.nuget.org/packages/Brick/

https://github.com/pennyfx/nuget-brick

I wasn't sure about the folder structure, so I dumped the files at the root of the project.  If you have a preferred location that is frequently used for web-apps then we can change that behavior.

**Comment by maitredede** [comment]
The usual location for scripts is ~/Scripts :)
