### ISSUE TITLE
Integration with other form elements could stand some work

### ISSUE THREAD

**Issue by fburleigh** [mozbrick/brick#54]
Hello.  First, thanks for the open stuff.  I think I'd much prefer this library to some others.

Now, here's the trouble.  On a simple, existing, uninteresting form I added a date picker.  It works!  What it doesn't (yet) do is "integrate": by that I mean crafting style to match the existing form isn't obvious, what with some extra wrapping with their own bordering and padding.  There's also some data format hinting in the pick element that should really be matched on other elements (email, number input) but we don't have info how to do that.

Your work is beta so in principle things like this are TODO.  I'm just ahead of the curve. ;-)  Thank you!

**Comment by sole** [comment]
Work on separating 'functional' from 'aesthetic' styles is in progress, not sure if that answers your question/plea, but you can keep track of that issue here: https://github.com/mozilla/brick/issues/46

**Comment by potch** [comment]
The `<x-datepicker>` contains an `<input>` element that can be styled to match your surrounding styles. Hope that helps!
