### ISSUE TITLE
clicking dates in next/previous month picks wrong date

### ISSUE THREAD

**Issue by skierpage** [mozbrick/brick#55]
On http://mozilla.github.io/brick/demos/datepicker/index.html , click to bring up the date picker, then click a grayed-out date from the next or previous month; for example, in September 2013, click the grayed-out 2 for October 2nd.

Result: instead of picking 2013-10-02, or advancing to October without selecting anything, it advances to October and picks whatever date is underneath where you clicked in the new month, in this case 2013-10-30. That's clearly the wrong behavior. If your click location is still gray in the new month, it does something weirder like picking a random date from that column; for example, in December 2013 click, click January 4 and it jumps to Feb 1st!

This in Firefox 23.0 on Ubuntu 13.04. The "Forcing polyfill UI view" does the right thing in Chromium 28.0.1500.71 Ubuntu 13.04

**Comment by pennyfx** [comment]
Fixed
