### ISSUE TITLE
Calendar doesn't switch to another month when clicks on a day outside of the current month

### ISSUE THREAD

**Issue by mcepl** [mozbrick/brick#58]
Just noticed when playing with the calendar component and looking at #55 that the [x-calendar element](http://mozilla.github.io/brick/demos/calendar/index.html) doesn't have this ability at all.

It could be probably possible to add this functionality with additional event handlers, but it would be awesome if it was available per default.

**Comment by dotch** [comment]
will be tracked in the calendar repo at https://github.com/mozbrick/brick-calendar/issues/6
