### ISSUE TITLE
Allow clicking on a specific date to create an event

### ISSUE THREAD

**Issue by operatorjen** [mozbrick/brick#6]
It would be good to allow a double-tap/click to open an event option where we can enter information. It would be even better if the event could allow me to add in custom HTML (if I want to include `<ul><li></li></ul>, <h1>, <form>` etc)

**Comment by pennyfx** [comment]
Which component does this relate to?

**Comment by operatorjen** [comment]
oh dammit... x-calendar!

**Comment by ldoubleuz** [comment]
Implemented as of 9a7a3f5e3ec03d5916ec31453b977eed0dcf05bc :)

Although it is not a built-in functionality of the component, I have included a demo in calendar/demo/calendar-demo.html of using the API hooks to do just this.
