### ISSUE TITLE
Confused by License

### ISSUE THREAD

**Issue by ghost** [mozbrick/brick#60]
I am confused by BSD license in package.json and suggestion of MPL 2.0 in the project root which is strongly copyleft. These are very much on opposite poles of the spectrum. The MPL 2.0 is likely to raise eyebrows if there is some idea of broader adoption. Some clarity appreciated.

**Comment by sole** [comment]
Hi!

Thanks for noticing. We'll make things consistent.

However, although "I am not a lawyer" I don't see issues with MPL2 and broader adoption. As far as I understand MPL2 is actually in between both sides, GPL and BSD.

"The MPL allows covered source code to be **mixed with other files under a different, even proprietary license**. However, code **files licensed under the MPL must remain under the MPL and freely available in source form**. This **makes the MPL a compromise between the MIT or BSD licenses**, which permit all derived works to be relicensed as proprietary, and the GPL, which requires the whole of a derived work, even new components, to remain under the GPL. By allowing proprietary modules in derived projects while requiring core files to remain open source, **the MPL is designed to motivate both businesses and the open-source community** to help develop core software."

(emphasis mine)

https://en.wikipedia.org/wiki/Mozilla_Public_License
http://www.mozilla.org/MPL/2.0/

So you can use Brick in your proprietary project but if you distribute it, you have to provide links to the source code of Brick, or provide the source yourself. Does it make sense? :-)

**Comment by ghost** [comment]
I think broader adoption may be hindered by such complication to be honest. These sorts of initiatives that reflect a trend and movement towards unencumbered open standards in my opinion should be the most liberal. I am not sure whether it is MPL because this is simply by default due to Mozilla's involvement or whether there has been any greater thought on the impact of commercial development and codebases. Its wonderful we have open standards, open dialog and contribution to something like this that should fundamentally change some of what we are doing. That said, this may not be satisfactory for developers to confront legal resources in their organizations to work out how this might be used in commercial projects where this only gets increasingly messy (on the basis of how many parties are involved in the creation of the code).

**Comment by sole** [comment]
That complication is pretty much the same as the MIT "complication" that asks you to preserve source authorship statements. I.e. give credit.

**Comment by ghost** [comment]
This is not equivalent. One is around the authorship/attribution where and the MPL is about applying one's own changes together with these sources while meeting the spirit of the MPL and making available the original sources. With BSD, there is minimal encumbrance. With MPL I cannot understand how one can practically apply the MPL within HTML to fulfill the requirements. If the license is MPL how could one do this in the context of serving a public web or mobile site? Hope someone at Mozilla is giving some appropriate thought to this.

**Comment by sole** [comment]
@fairwinds might I suggest you liberally add carriage returns, because it's really hard to read your answers? :-)

Also, the key to all this is distribution.

But I am not a lawyer. Are you?

**Comment by potch** [comment]
@fairwinds I'll raise these issues and we'll discuss whether a license that does not require Source Disclosure makes sense for the project. The goal of the project is to make it easier to build apps, and I'll ask if MPL hinders that effort. Our legal team doesn't control the project by any means, but they're the smart people to whom I defer on these matters :hammer:

**Comment by ghost** [comment]
Apologies on carriage returns. Expected github to look after leaving
text in a readable state. Hope this is better for you.

Nope on the lawyer question. Just a programmer and developer that likes
the direction I see in web standards and what you folks are doing.

That said, it is prudent to give licensing consideration and I of course
want  to live up to the spirit of open sources and comply with license
requirements. Having trouble with this because I cannot see an
appropriate way of applying the MPL together with sources I may have to
modify anything. We are talking widgets here and there will be no doubt
be a variety of iterations that will come from a variety of sources in this
regard.

So while determining licensing for the project, I want there to be both
thought and consideration on the practical implications of the licensing
choice you are making upon a developer. We are the target audience are
we not? It is a practical issue and I am only one of any number of folks
that will have an interest but will want clarity on how to make
changes or receive guidance on how to use what you are creating in
the apps and our work. I think that is reasonable, don't you?

**Comment by sole** [comment]
@fairwinds it's strange, it might be a github bug. I'd suggest contacting them if you have the time, they'll fix issues quickly. That said, thanks for explaining. I see your position.

And I think @potch's answer is the most sensible one. Legal should look into this; let developers worry about development :-D

**Comment by ghost** [comment]
@patch That is great. I am just hoping to be heard. The project is young
and licensing frames the how, what, and why of the use of it. It
will either encourage or discourage contribution to the work as a
result. If it is transparent and unencumbered, folks are really going to
love this. If not, I believe it may only lead to the perpetuation of
repos and projects that make this sort of work easier to work with for
every need.

There is a real opportunity to build a great common repository of
generalized UI hand in hand with standards. Just wish to see that it can be
as transparent as the standards to apply.

@patch, @sole Appreciate the dialog also. So thank you for being
receptive to the point of view.

**Comment by potch** [comment]
@fairwinds thanks for caring enough to bring it up!

**Comment by ghost** [comment]
Hello. Any news on this?

**Comment by potch** [comment]
@fairwinds the intent is to move the the Apache 2 License. You can expect that migration in an upcoming release.

**Comment by ghost** [comment]
This is great news, is there an ETA? I'd really like to be digging into this soon. I like the project and the possibilities for the web.

**Comment by potch** [comment]
I'd expect in the next few weeks. We will be spinning at least one new
build in that timeframe.

**Comment by sole** [comment]
@potch, it would be great to hear about why Apache 2 vs MPL2. Just so we get a bit more literate licensing-wise :D

ta!

**Comment by fwenzel** [comment]
"New projects which are Mozilla Code may choose either the MPL 2.0 or the Apache License 2.0. No other license is acceptable, because Mozilla is committed to using modern open source licenses with patent grant clauses."

http://www.mozilla.org/MPL/license-policy.html

MPL2 is copyleft while Apache is not, and to enable the most widespread use of Brick, requiring contributions back to the project may unnecessarily limit the use of it.

That said, the social convention of contributing back to a project like this, as well as the simplicity of contributing tags and code to x-tags, hopefully encourage contributions more than a copyleft clause ever could.

**Comment by potch** [comment]
@fwenzel said it better than I could!

**Comment by potch** [comment]
Apologies on the slowness to fix this. The license has been set to Apache 2 in both the package.json and LICENSE file.
