### ISSUE TITLE
Fresh coat of paint

### ISSUE THREAD

**Issue by gkoberger** [mozbrick/brick#61]
I felt Brick could use a bit of a refresh.

![main](https://f.cloud.github.com/assets/381393/1178058/7af0e454-219b-11e3-9ce6-c8fe654c13fb.png)

Clicking any of the types in "See it in action" would make the demo appear on the actual phone. The code would show up on the right, and any controls ("Flip Me") would show up on the actual UI.

The top bar and the text at the bottom could use a little love, too -- but my 30 minute limit ran out :)

(Here's the PSD: http://cl.ly/1J3f2Z1A0o2r)

**Comment by gkoberger** [comment]
Or:

![main2](https://f.cloud.github.com/assets/381393/1184264/ddfa85ee-2242-11e3-9e81-9961543489e2.png)

**Comment by potch** [comment]
daaang.

**Comment by fwenzel** [comment]
Oooh

**Comment by fwenzel** [comment]
Melikes.

**Comment by potch** [comment]
I smell a 1.0 re-vamp, don't you?

**Comment by tofumatt** [comment]
<3s for @gkoberger

**Comment by tofumatt** [comment]
I would be into integrating the PSD into the actual HTML, unless anyone else has claimed this task?
