### ISSUE TITLE
NS_ERROR_XPC_BAD_OP_ON_WN_PROTO: Illegal operation on WrappedNative prototype object

### ISSUE THREAD

**Issue by nickdesaulniers** [mozbrick/brick#63]
specifically this line in my bundle:

``` javascript
for (H in B) w.TouchEvent.prototype[H] = B[H], Object.defineProperty(w.TouchEvent.prototype, H, B[H]);
```

**Comment by potch** [comment]
@csuwldcat looks like an issue with gestures. If this is affecting FirefoxOS we need to fix asap.

**Comment by nickdesaulniers** [comment]
If I separate the lines, specifically this line is the problem:

``` javascript
Object.defineProperty(w.TouchEvent.prototype, H, B[H]);
```

**Comment by nickdesaulniers** [comment]
looks like:

``` javascript
xtag.addEvent(document, 'tap', function (e) {
  console.log(JSON.stringify(e.touches), typeof e.touches[0].type); // {...}, "undefined"
});
```

works if I just comment out the line from my previous comment. @csuwldcat

**Comment by potch** [comment]
@csuwldcat any traction on this? Need to fix people using the current build.

**Comment by csuwildcat** [comment]
It was fixed and tagged yesterday ;)

**Comment by nickdesaulniers** [comment]
@csuwldcat , is it live in the production bundles?

**Comment by csuwildcat** [comment]
It is, Brick probably needs to update

**Comment by sole** [comment]
Ooops, now I'm getting it too!

**Comment by potch** [comment]
Can someone encountering this re-test? We've spun 1.0beta8 to address this.

**Comment by nickdesaulniers** [comment]
@potch , ok I'll give it a spin after lunch.

**Comment by nickdesaulniers** [comment]
¡Ay, caramba! It's La Bamba!

**Comment by sole** [comment]
@nickdesaulniers I hate you. I can't stop humming La Bamba since I read your comment. GRRRRRRR!!!
