### ISSUE TITLE
Remove all faux-Shadow-DOM-ish code

### ISSUE THREAD

**Issue by csuwildcat** [mozbrick/brick#64]
Some components like iconbutton and tooltip implement their own faux-Shadow-DOM-ish wrap code. Further, even these faux-shadow wraps are different from component to component. This makes utilization of the component more difficult, and forces user to learn one-off DSLs for each one.

**Comment by fwenzel** [comment]
oh? Link to code please?

**Comment by csuwildcat** [comment]
I already referenced two examples: Tooltip (https://github.com/mozilla/brick/blob/master/component/tooltip/src/tooltip.js) and Iconbutton (https://github.com/mozilla/brick/blob/master/component/iconbutton/src/iconbutton.js)

These two components could stand to see radical simplification. Tooltip is (with comments) 1600 lines. We need a sheet of best practices, and to be adherent to them as much as possible.

**Comment by fwenzel** [comment]
Thanks! I'll leave the closer analysis up to Potch and Arron, but 1600 lines is impressive.

**Comment by potch** [comment]
1600 lines is a bit of a misrepresentation, given the sheer volume of documentation in tooltip. Tooltip does fairly complex logic to ensure that the content a) points to the requested target, b) remains in the viewport, and c) tracks properly when the target is moved out of the viewport. The code may be slightly over-engineered and could use a refactor, but I'm unfamiliar with a best practice that refers to LOC caps.

**Comment by potch** [comment]
As for the 'shadow-DOM-ish code', there are elements that the user may want to manipulate (for example the content of a tooltip) without needing to traverse the structural DOM of the tooltip itself. The properties you refer to are simply shortcuts straight to the inner DOM. Such shortcuts exist throughout the DOM and I don't consider being humane to developers something in violation of any best practices. We should, however, be consistent in naming.

**Comment by csuwildcat** [comment]
As for the 1600 LOC vs number of comment lines, I had already stipulated
that in my comment. Still, I reviewed the code and believe its can be
_dramatically_ slimmed.

On the fake-shadow-wrap front, we're confusing the idea of node accessors
(common in the DOM) with forced DSLs required to step around our
wrap-hijacking of contents. Consider a <select>, am I prevented from using
appendChild() to add <option> elements, or forced to use some special
accessor to get at elements inside it? Of course not. Specifically with
respect to Tooltip, I've reviewed the wrap portion and feel confident all
the same functionality can be offered without using it.

Introducing one-off DSLs per-component for anything that attempts to feint
standard-ish behavior is an anti-pattern - which is a general point aligned
with the thinking of the Google folks and other Web Components standard
participants.

**Comment by potch** [comment]
Please stop referring to a few functions named something slightly different than the DOM as a DSL. Also, Domain Specific Languages aren't even a bad thing if you need something that works well in, well, a specific domain.

**Comment by csuwildcat** [comment]
The problem isn't custom functions on custom elements Potch, the problem is
treating a node in markup like you can use all the normal DOM manipulation
methods to interact with it, then flipping the script by forcing people to
go through unexpected, one-off methods to perform what they expect.

Please name a single element in all of HTML where the position of your
markup does not match the leveling of elements in imperative code. To have
the nodes you just declared obfuscated with an after-the-fact wrapper tree,
you are forced to crawl around the cruft with one-off, per-component,
non-standard accessors in post-parse JS interaction. It's an obtuse
anti-pattern, and we should stay away from it.

**Comment by pennyfx** [comment]
We don't have shadowDOM yet so we are forced to use DOM visible wrappers at times to get desired functionality.   Providing a few access points to specific locations within the element is a helpful work around for the time being.   Once we have shadowDOM then these helpers can be deprecated.

**Comment by csuwildcat** [comment]
A few things are wrong with that:
- If we create a get-to-the-real-content wrapper mechanism, the system and
  the accessors should be normalized from tag to tag. That's API 101 - don't
  make 10 separate systems that do the same things and give them all
  different accessor/method names.
- Arron, your statement that we'll simply uplift the API to use Shadow DOM
  when ready is technically perilous and is likely to end in a tangled mess.
  I have serious doubts we'll be able to paper over it like that.
- As a point of fact, the wraps aren't necessary to provide the Tooltip's
  current features/behavior.

**Comment by potch** [comment]
I'm all-for making shortcut accessors consistenly named. Just remember that `document.body` > `document.documentElement.childNodes[1]` :)

**Comment by csuwildcat** [comment]
@potch cool, let's set aside some time this week to discuss a strategy/mechanism for offering a consistent API for wrap situations that will provide a path for seamless integration of _real_ Shadow DOM functionality. If we can get this in place and use it across our custom elements, we can be far more confident in our ability to utilize Shadow DOM under the covers in the future, without fracturing the APIs we create for them today.

Your citation of two different routes to the same node is code-accurate, but isn't relevant to the issue at hand: breaking the markup <--> DOM parity model. If a developer uses the following markup: `<body><h1>foo</h1></body>`, they would never expect `document.body.firstElementChild` to return a `<div>`. My point: if we're going to break the standard model, we should be sure of the following:
- It is absolutely necessary when we choose to do it
- It exposes a common interface that is familiar and predictable from element to element
- The system is able to flexibly integrate new, standard APIs under the covers when they land (Shadow DOM, etc) without forcing avoidable, breaking changes.

If we do the above 3 things, there's no problem with wrapping things with additional markup when a component requires it ;)

**Comment by pennyfx** [comment]
As potch said we are creating shortcut accessors to give users access to the internals of the element.  While giving them consistent names has merit, it can also create ambiguity of what 'content' means for each control.  

For example,  `x-appbar` has `heading` and `subheading` accessors which are obvious and self-documenting.  I'm not convinced that changing these to `content` and `subcontent` for the sake of "standard api" is the best choice.  It ends up creating an arbitrary rubric that then all elements have to find some way to conform to.  There will aways be exceptions to these rules, especially as elements become more complex.   I'm on the side of each element using accessors that make sense to its functionality and domain.   This means each element has a documented API that is the primary way to interact with it.   Resorting to native DOM APIs may result in unexpected behavior.

**Comment by csuwildcat** [comment]
Arron, your example would not be a case of the issue at hand. We should
meet this week to clarify everything.

**Comment by rudasn** [comment]
...So what's the status on this?

**Comment by potch** [comment]
Still bikeshedding :) Working on some conventions that will be consistent between elements.

**Comment by potch** [comment]
Brick 2 will be using proper Shadow DOM, so issues about encapsulation and exposure should be much more manageable.
