### ISSUE TITLE
Use common DOM nomenclature for properties and methods

### ISSUE THREAD

**Issue by csuwildcat** [mozbrick/brick#65]
We should be adherent to common DOM nomenclature whenever possible, for instance:

In iconbutton, there are the properties contentEl and iconEl. Nowhere in the DOM are element property getters truncated, as evidenced by: parentElement, firstElementChild, lastElementChild, etc.

**Comment by potch** [comment]
Fair point. Will tune up.

**Comment by pennyfx** [comment]
Moving:  https://github.com/x-tag/iconbutton/issues/1
