### ISSUE TITLE
Download page should offer unminified versions too

### ISSUE THREAD

**Issue by mythmon** [mozbrick/brick#66]
Some projects (like SUMO) prefer to put unminified files into source control, for ease of development, and then have a build process that minifies everything together.

It would be great if the download page that lets you build a custom bundle had a checkbox (probably checked by default) that lets you toggle minification.

**Comment by fwenzel** [comment]
Are you writing a patch? <3

**Comment by mythmon** [comment]
Not yet, but I might when I'm done playing with d3! :dancer:

**Comment by potch** [comment]
A good idea indeed!

**Comment by lisp-ceo** [comment]
Buuuump! :)

**Comment by pennyfx** [comment]
Our build system outputs unminified files now.  Just need to add an option to the custom bundle builder to use those files.    https://github.com/mozilla/brick/issues/98

**Comment by pennyfx** [comment]
Added checkbox to download page that allows downloading of unminified Brick.  
https://github.com/mozilla/brick/commit/87a4a8490f566483cf79750d8cdb825592bfc597
