### ISSUE TITLE
Add Brick to JSFiddle and integrate JSFiddle with Brick's site

### ISSUE THREAD

**Issue by fwenzel** [mozbrick/brick#73]
JSFiddle would be a great way for people to learn how to use Brick and try it out. I see two parts of this:
- adding it to JSfiddle itself, which I assume is easy, though I do wonder how we can push updates out when there's a new release of the library? @zalun ?
- adding it to the Brick site somehow, so that people can click a button and try things out immediately. I am not sure if there's an API for it of sorts, but maybe we can write "simple" code that'll take a brick code example and instantly spin up a new fiddle with it?

**Comment by zalun** [comment]
The best option for updates is to create some sort of edge (nightly) version which will get updated frequently. Some old fiddles might not work if changes will be backward incompatible. There is also an option to create a stable version plus the egde one.

These should be placed on some sort of CDN (github pages are fine, but not the repository's RAW view)

JSFiddle is able to read prepared github directory or directly from POST request. 
- http://doc.jsfiddle.net/use/github_read.html
- http://doc.jsfiddle.net/api/post.html

These will not let you to display an embedded version - for that the fiddle needs to be saved.
It would be good to create a user called "brick" and place all examples inside (http://doc.jsfiddle.net/basic/introduction.html#fiddle-options). All named examples will be displayed in http://jsfiddle.net/user/brick/ 
Avatar is taken from Gravatar only so pick a good email :)

**Comment by potch** [comment]
@zalun If GitHub pages are fine, then the canonical URLs are:

JS: http://mozilla.github.io/brick/dist/brick.js
CSS: http://mozilla.github.io/brick/dist/brick.css

**Comment by zalun** [comment]
Yest it's good - currently fixing the Dependencies table to allow CSS inly links

**Comment by zalun** [comment]
Please check if it's working on http://alpha.jsfiddle.net/

**Comment by zalun** [comment]
It is on the production site now as "Brick edge"
