### ISSUE TITLE
CSP violations

### ISSUE THREAD

**Issue by nickdesaulniers** [mozbrick/brick#75]
![screen shot 2013-10-02 at 11 49 05 am](https://f.cloud.github.com/assets/1823839/1256297/621c1780-2b93-11e3-83f3-ae8d96288735.png)

This is a problem for privileged (packaged) apps.

**Comment by fwenzel** [comment]
eval?

**Comment by pennyfx** [comment]
@fwenzel     There is an eval line in the polyfill.  

https://github.com/x-tag/core/blob/master/lib/web-components-polyfills.js#L1912

**Comment by fwenzel** [comment]
Might need to analyze an unminified version to see where these warnings are coming from and to see if this harms the use of brick in packaged apps!

**Comment by nickdesaulniers** [comment]
This is blocking [the IRC app](https://github.com/nickdesaulniers/fxos-irc/issues/24), any way we could get this fixed pre-summit? cc @potch

**Comment by nickdesaulniers** [comment]
I beautified the source.  The top and bottom look like noise, the second is the obvious culprit:
![screen shot 2013-10-02 at 4 20 12 pm](https://f.cloud.github.com/assets/1823839/1258254/50f90ec4-2bb9-11e3-85bb-f263d881686b.png)

[Full Validation Report](https://marketplace.firefox.com/developers/upload/8957f74bd962424b89b721a04190b4f0).

See @pennyfx 's comment.

**Comment by csuwildcat** [comment]
@pennyfx can we stop including HTMLImports in our polyfill?

**Comment by pennyfx** [comment]
@csuwldcat  Technically yes, we just have to remove the HTML imports lines from the build.  https://github.com/x-tag/core/blob/master/Gruntfile.js#L13

What about the other CSP issues though?

**Comment by csuwildcat** [comment]
@pennyfx I don't believe those other violations are actually correct - there is nothing there that evaluates code dynamically as banned by CSP: https://developer.mozilla.org/en-US/Apps/CSP

**Comment by potch** [comment]
@pennyfx The other warnings are just that- warnings. They just flag possible locations where someone could pass the string "script" to createElement(). They don't disqualify anyone from a review, but let reviewers and devs know they should look to make sure.

**Comment by pennyfx** [comment]
@potch I'm creating another tag that does not have htmlimports.     [0.8.3-noimports](https://github.com/x-tag/core/tree/0.8.3-noimports)   They can use this build for summit.

**Comment by fwenzel** [comment]
Nice, good work @pennyfx . Do you manually remove the offending code, or is that step reproducible?

**Comment by pennyfx** [comment]
Removed a few lines from the gruntfile and rebuilt.

**Comment by nickdesaulniers** [comment]
Do x-tags add any script elements to the DOM?

**Comment by csuwildcat** [comment]
X-Tag itself does not, I believe any and all CSP issues would be raised out
of the polyfill we share with Google.

**Comment by fwenzel** [comment]
@pennyfx did you fix (or, stop-gap) this? If so, please close the issue, thanks!

**Comment by nickdesaulniers** [comment]
I think it unblocked me, but broke Safari.

**Comment by potch** [comment]
@nickdesaulniers what sort of Safari breakage are you seeing?

**Comment by nickdesaulniers** [comment]
Cards weren't rendering, IIRC.

**Comment by nickdesaulniers** [comment]
This is still an issue for privileged packaged apps.

**Comment by potch** [comment]
@nickdesaulniers any chance this is working for you?

**Comment by nickdesaulniers** [comment]
@potch , just built from source, it looks good!  let me know when it's live in production.

**Comment by potch** [comment]
0.9.0 is out and working!

**Comment by nickdesaulniers** [comment]
This needs to be reopened.  A bundle built from the components still has this in 0.9

**Comment by csuwildcat** [comment]
@nickdesaulniers which CSP violation persists? All of them?

**Comment by nickdesaulniers** [comment]
``` javascript
r += "\n//# sourceURL=" + o + "\n", eval.call(window, r)
```

**Comment by csuwildcat** [comment]
@nickdesaulniers looks like `bower update` output was cached, Potch is flushing that cache and respinning. You should be on track shortly, look from an update from them here.

**Comment by nickdesaulniers** [comment]
brick 0.9.1 fixed this, thanks for the quick response @csuwildcat & @potch .
