### ISSUE TITLE
Who posseses the copyright for this repo?

### ISSUE THREAD

**Issue by nickdesaulniers** [mozbrick/brick#76]
I one was to reuse this, we need to cite the copyright holder.  This is not listed in the license.

[CC](https://github.com/nickdesaulniers/fxos-irc/issues/17)

**Comment by potch** [comment]
Brick is presently MPL2, and coprighted to the Mozilla Corporation. I'd like to investigate whether Apache 2 is a better fit for the project, and whether we should use an AUTHORS file to better represent contributions. I've updated the LICENSE file to reflect the current state of affairs.

**Comment by potch** [comment]
WHO RUN BRICKTOWN

**Comment by fwenzel** [comment]
Truth
