### ISSUE TITLE
Both sides of a Flipbox are the same height.

### ISSUE THREAD

**Issue by ghost** [mozbrick/brick#78]
If one side of the Flipbox has a lot of content, and you flip to the other side with less content, the user has to scroll up. In extreme cases, they have to some intensive scrolling.

This may also affect the other view types (Decks, Slideboxes, etc.), but I haven't verified this.

**Comment by fwenzel** [comment]
Are you saying that they are the same height but shouldn't be? I think the point of the flipbox is to be two sides of the same "card", which is then obviously the same size. If you have vastly differing content sizes, you might need to force a shorter max-height and handle overflow?

**Comment by ghost** [comment]
I figured that this was the designed behavior. I'm using a Flipbox to hold two very differently sized pages, and flipping between the two is very awkward. 

Do the Deck and Slidebox views act the same way? Is there a better view to be using for variable sized pages? Maybe an x-layout embedded on one side of the Flipbox?

**Comment by potch** [comment]
@dtk it probably makes sense for the inner 'side' element of the flipbox to be limited to the size of the flipbox itself and implement scrolling. This is a good example where our default behavior could use some work. I'm going to leave this issue open to track that fix. Thanks!

**Comment by potch** [comment]
tracking this here: https://github.com/mozbrick/brick-flipbox/issues/4
