### ISSUE TITLE
New default skin appearance for components

### ISSUE THREAD

**Issue by potch** [mozbrick/brick#87]
We need a sexy default appearance!
- [x] appbar
- [x] calendar
- [x] deck
- [x] flipbox
- [x] layout
- [x] slidebox
- [x] slider
- [x] tabbar
- [x] toggle
- [x] tooltip

**Comment by aarondruck** [comment]
Appbar
![appbar 2x](https://f.cloud.github.com/assets/2692810/1354408/1256d312-3754-11e3-9da0-821976cbb73f.png)
![appbar](https://f.cloud.github.com/assets/2692810/1354409/12891f48-3754-11e3-8cc3-cd9851d31556.png)

**Comment by aarondruck** [comment]
Body
![body](https://f.cloud.github.com/assets/2692810/1354411/197382da-3754-11e3-98e0-ec3da9d927d1.png)
![body 2x](https://f.cloud.github.com/assets/2692810/1354412/198b307e-3754-11e3-97a1-416e317e9b42.png)

**Comment by aarondruck** [comment]
Buttons
![buttons 2x](https://f.cloud.github.com/assets/2692810/1354415/21f7c506-3754-11e3-89e1-d268bb1e3bc3.png)
![buttons](https://f.cloud.github.com/assets/2692810/1354416/2211a980-3754-11e3-8a4e-aab1ab7b92bc.png)

**Comment by aarondruck** [comment]
Buttons 2
![buttons2](https://f.cloud.github.com/assets/2692810/1354418/278931e4-3754-11e3-81c5-31a2ce67b4a7.png)
![buttons2 2x](https://f.cloud.github.com/assets/2692810/1354419/2789b5c4-3754-11e3-8e96-18f49d59e29b.png)

**Comment by aarondruck** [comment]
Calendar
![calendar](https://f.cloud.github.com/assets/2692810/1354420/2d195ce2-3754-11e3-91fe-3641fba9fe4d.png)
![calendar 2x](https://f.cloud.github.com/assets/2692810/1354421/2d19dde8-3754-11e3-89b5-6e052a58d126.png)

**Comment by sole** [comment]
wow this is on fire!!! :fire:

**Comment by aarondruck** [comment]
Date Picker
![datepicker 2x](https://f.cloud.github.com/assets/2692810/1354422/32ef0a36-3754-11e3-9d8e-00499c0431e6.png)
![datepicker](https://f.cloud.github.com/assets/2692810/1354423/32ef4da2-3754-11e3-98d2-59b1c574775a.png)

**Comment by aarondruck** [comment]
Modal
![modal 2x](https://f.cloud.github.com/assets/2692810/1354427/3862c782-3754-11e3-8109-9f83642cb3b7.png)
![modal](https://f.cloud.github.com/assets/2692810/1354428/38657932-3754-11e3-99d2-7f65d1d20f35.png)

**Comment by aarondruck** [comment]
Tabbar
![tabbar 2x](https://f.cloud.github.com/assets/2692810/1354429/3db46d8a-3754-11e3-8c53-7e679653c1dc.png)
![tabbar](https://f.cloud.github.com/assets/2692810/1354430/3db4e346-3754-11e3-9fa1-65e613a2f7e3.png)

**Comment by aarondruck** [comment]
Widgets
![widgets 2x](https://f.cloud.github.com/assets/2692810/1354431/4421bab0-3754-11e3-8ca4-f47fdb2bd4b2.png)
![widgets](https://f.cloud.github.com/assets/2692810/1354432/4421d310-3754-11e3-9b22-80104090c762.png)

**Comment by aarondruck** [comment]
Adding details here: https://github.com/mozilla/brick/wiki/Brick-Style-Guide

**Comment by potch** [comment]
All done in 0.10.0
