### ISSUE TITLE
`x-calendar` `controls` attribute doesn't seem to work

### ISSUE THREAD

**Issue by mattbasta** [mozbrick/brick#9]
Leaving off the `controls` attribute doesn't seem to affect whether `makeControls` is called, and controls are always added.

**Comment by ldoubleuz** [comment]
This is intentional so that switching the attribute doesn't require node-rebuilding. However, I could change it so that the controls aren't added until the first time controls is set to true.

**Comment by mattbasta** [comment]
Even on the first load, though. Having the static attribute in the HTML doesn't seem to change whether the controls are displayed or not; they're always added.

**Comment by ldoubleuz** [comment]
That's...what I just said?

**Comment by mattbasta** [comment]
I guess I don't understand. How do I turn them off then?

**Comment by ldoubleuz** [comment]
No need, I've already implemented the change I mentioned.

Fixed as of d58eba983606ad6f3794b73646c4550b4ae24dc4
