### ISSUE TITLE
Tab bars are not rendered correctly in 1.2

### ISSUE THREAD

**Issue by nickdesaulniers** [mozbrick/brick#95]
Note, I am adding them dynamically after the first one which is static.
![2013-10-24-14-35-02](https://f.cloud.github.com/assets/1823839/1401727/42dfcb2e-3cdb-11e3-928a-c87e016ae326.png)

**Comment by potch** [comment]
Nick, can you confirm this issue still occurs with the latest Brick?

**Comment by nickdesaulniers** [comment]
Looks like something changed in regards to which tab is the selected tab?  When the app loads, I see the single tab with no content, but if I click the single tab, the content is shown.
![screen shot 2014-05-05 at 5 07 48 pm](https://cloud.githubusercontent.com/assets/1823839/2884810/8eb797d8-d4b2-11e3-8646-abe260647ada.png)

**Comment by nickdesaulniers** [comment]
For future travelers, see https://github.com/nickdesaulniers/fxos-irc/commit/16f016b3487cad83b2aaeec6b48f18b37c4d44fc
