### ISSUE TITLE
Land gestures on the X-Tag side and make them available as an optional Brick include

### ISSUE THREAD

**Issue by csuwildcat** [mozbrick/brick#97]
Gestures need to land in X-Tag and be offered as an optional include for Brick packages.

**Comment by sole** [comment]
Might I ask... why optional? can't they be enabled by default? Example, in the `x-deck`, to switch left/right?

**Comment by pennyfx** [comment]
I think he means they will only be packaged together if a component
requires gestures for certain actions.  Gestures are not part of xtag core.

**Comment by potch** [comment]
Brick is no longer using x-tag, so this is no longer valid.
