### ISSUE TITLE
datepicker is broken today

### ISSUE THREAD

**Issue by LukeStonehm** [mozbrick/brick#99]
Ok, so I know it's Halloween, but we don't need this. It's broken for us on multiple sites, using separate copies of brick

![broken_datapicker](https://f.cloud.github.com/assets/5001686/1446333/d51c9f6c-4235-11e3-95a3-dbf957aa32d5.png)

As you can see, the calander only has one row of dates...

**Comment by nahojd** [comment]
I second that, it worked yesterday, and it will work tomorrow (confirmed by changing the computer date). It just doesn't work today. Makes you wonder what other dates will make it go bananas...

It also skips directly from October to December, then to January, and then to March, and so on. And it's often - but not always - impossible to go back. So, pretty weird behaviour.

**Comment by LukeStonehm** [comment]
Cool, good to know that I'm not going insane :)

**Comment by fwenzel** [comment]
Apologies, fix is in the works, in issue #96.
